name: CD

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    branches: [main, dev]
    types:
      - completed

jobs:
  test:
    env:
      MEMORY_LIMIT_MB: 4096

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Pull Docker image
      run: docker pull myashka/big_data_app:latest

    - name: Start services
      run: |
        DATABASE_URL="${{ secrets.DATABASE_URL }}" \
        DB_NAME="${{ secrets.DB_NAME }}" \
        DB_USER="${{ secrets.DB_USER }}" \
        DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
        docker-compose up -d
        
    - name: Wait for services to be ready
      run: sleep 30

    - name: Execute unit tests inside Docker container
      run: docker-compose exec -T app poetry run pytest src/unit_tests/

    - name: Execute integration tests inside Docker container
      run: docker-compose exec -T app poetry run pytest --log-cli-level=DEBUG tests/
      # run: docker-compose exec -T app poetry run pytest tests/

    - name: Get Docker Compose Logs
      if: always()
      run: docker-compose logs

    - name: Stop services
      if: always()
      run: docker-compose down